### PR TITLE
Sub-Team Auth: User Registration

### PR DESCRIPTION
**Pull request by DavidHODs**
This resolves issue #163 

Users can now register after supplying required details

### CODE REVIEW

**Comment by farouqu** [comment]
Could not find the code that solves the issue you stated

**Comment by DavidHODs** [comment]
> Could not find the code that solves the issue you stated

And none of my team mates told me this..

Please give me like 1hr to set up andpush again

**Comment by DavidHODs** [comment]
> > Could not find the code that solves the issue you stated
> 
> And none of my team mates told me this..
> 
> Please give me like 1hr to set up andpush again

Found it

Created a pull request from the dev branch instead of main

**Comment by farouqu** [comment]
Your PR 

> > > Could not find the code that solves the issue you stated
> > 
> > 
> > And none of my team mates told me this..
> > Please give me like 1hr to set up andpush again
> 
> Found it
> 
> Created a pull request from the dev branch instead of main

Your PR only shows update to the github workflow file

**Comment by DavidHODs** [comment]
Yes

I'll close that one and open another one in few mins

**Comment by DavidHODs** [comment]
I've opened a new pull request

The code is the commit link "end point for user registration"

**Pull request closed without merging**
